/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 16-ноя-2022 0:38:44 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Address" CASCADE
;

DROP TABLE IF EXISTS "Author" CASCADE
;

DROP TABLE IF EXISTS "Category" CASCADE
;

DROP TABLE IF EXISTS "Order" CASCADE
;

DROP TABLE IF EXISTS "Order_address" CASCADE
;

DROP TABLE IF EXISTS "Person" CASCADE
;

DROP TABLE IF EXISTS "Person_address" CASCADE
;

DROP TABLE IF EXISTS "Product" CASCADE
;

/* Create Tables */

CREATE TABLE "Address"
(
	"Additional_info" varchar(100) NULL,
	"City" varchar(30) NULL,
	"Country" varchar(30) NULL,
	"Details" varchar(50) NULL,
	"House_number" integer NULL,
	"Postal_code" varchar(12) NULL,
	"Street" varchar(50) NULL,
	"Street_number" integer NULL,
	"AddressID" integer NOT NULL,
	"Person_addressID" integer NOT NULL,
	"Order_addressID" integer NOT NULL
)
;

CREATE TABLE "Author"
(
	"Alternative_name" varchar(50) NULL,
	"Author_info" varchar(250) NULL,
	"Date_of_birth" date NULL,
	"Date_of_death" date NULL,
	"Name" varchar(30) NULL,
	"Surname" varchar(30) NULL,
	"AuthorID" integer NOT NULL
)
;

CREATE TABLE "Category"
(
	"Category_readable_name" varchar(50) NULL,
	"Type" varchar(30) NULL,
	"CategoryID" integer NOT NULL,
	"ProductID" integer NOT NULL
)
;

CREATE TABLE "Order"
(
	"Date_due_to" date NULL,
	"Date_rent_from" date NULL,
	"Description" varchar(250) NULL,
	"Order_date" date NULL,
	"Quantity" integer NULL,
	"OrderID" integer NOT NULL,
	"PersonID" integer NULL
)
;

CREATE TABLE "Order_address"
(
	"Order_addressID" integer NOT NULL,
	"OrderID" integer NOT NULL
)
;

CREATE TABLE "Person"
(
	"Created_at" date NULL,
	"Email" varchar(50) NULL,
	"Name" varchar(30) NULL,
	"Password" varchar(100) NULL,
	"Phone_number" integer NULL,
	"Role" varchar(20) NULL   DEFAULT 'ROLE_USER',
	"Surname" varchar(30) NULL,
	"Updated_at" date NULL,
	"Username" varchar(30) NULL,
	"PersonID" integer NOT NULL
)
;

CREATE TABLE "Person_address"
(
	"Person_addressID" integer NOT NULL,
	"PersonID" integer NOT NULL
)
;

CREATE TABLE "Product"
(
	"Buy_price" numeric NULL,
	"Date_of_issue" date NULL,
	"Description" varchar(250) NULL,
	"Rent_price" numeric NULL,
	"Title" varchar(50) NULL,
	"ProductID" integer NOT NULL,
	"AuthorID" integer NULL,
	"OrderID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Address" ADD CONSTRAINT "PK_Address"
	PRIMARY KEY ("AddressID")
;

ALTER TABLE "Author" ADD CONSTRAINT "PK_Author"
	PRIMARY KEY ("AuthorID")
;

ALTER TABLE "Category" ADD CONSTRAINT "PK_Category"
	PRIMARY KEY ("CategoryID")
;

ALTER TABLE "Order" ADD CONSTRAINT "PK_Order"
	PRIMARY KEY ("OrderID")
;

ALTER TABLE "Order_address" ADD CONSTRAINT "PK_Order_address"
	PRIMARY KEY ("Order_addressID")
;

ALTER TABLE "Person" ADD CONSTRAINT "PK_Person"
	PRIMARY KEY ("PersonID")
;

ALTER TABLE "Person_address" ADD CONSTRAINT "PK_Person_address"
	PRIMARY KEY ("Person_addressID")
;

ALTER TABLE "Product" ADD CONSTRAINT "PK_Product"
	PRIMARY KEY ("ProductID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Person_address"
	FOREIGN KEY ("Person_addressID") REFERENCES "Person_address" ("Person_addressID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Address" ADD CONSTRAINT "FK_Address_Order_address"
	FOREIGN KEY ("Order_addressID") REFERENCES "Order_address" ("Order_addressID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Category" ADD CONSTRAINT "FK_Category_Product"
	FOREIGN KEY ("ProductID") REFERENCES "Product" ("ProductID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Order" ADD CONSTRAINT "FK_Order_Person"
	FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Order_address" ADD CONSTRAINT "FK_Order_address_Order"
	FOREIGN KEY ("OrderID") REFERENCES "Order" ("OrderID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Person_address" ADD CONSTRAINT "FK_Person_address_Person"
	FOREIGN KEY ("PersonID") REFERENCES "Person" ("PersonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Author"
	FOREIGN KEY ("AuthorID") REFERENCES "Author" ("AuthorID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Order"
	FOREIGN KEY ("OrderID") REFERENCES "Order" ("OrderID") ON DELETE No Action ON UPDATE No Action
;
